name: CI

on:
  push:
    branches:
      - main
      - 'features/*'
    paths:
      - 'core/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'core/**'
      - '.github/workflows/ci.yml'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: v2.6.x

      - name: Check formatting
        run: deno fmt --check
        working-directory: core

      - name: Check lint
        run: deno lint
        working-directory: core

      - name: Check types
        run: deno task check
        working-directory: core

      - name: Run tests
        run: deno task test
        working-directory: core

      - name: Check coverage minimum
        run: deno task coverage:check
        working-directory: core
